### ISSUE TITLE
rpki-validator-app crashes with java.lang.StackOverflowError exception

### ISSUE THREAD

**Issue by tomkap** [RIPE-NCC/rpki-validator#18]
rpki-validator-app version: 2.21
java version "1.7.0_91"
OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-1~deb7u1)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)

Output:
`Exception: java.lang.StackOverflowError thrown from the UncaughtExceptionHandler in thread "main"`

**Comment by omuravskiy** [comment]
Thanks, tomkap,

We have fixed several memory-related issues in the 2.22-SNAPSHOT version.

For your issue, could you post the rest of the exception message, the stacktrace specifically, if you have it?

If you want to run stable version, then I suggest you stick with 2.17, until 2.22 is released.
Or you may try 2.22-SHAPSHOT (just pick up latest commit from master branch, if you are building it yourself).

Cheers,
Oleg

**Comment by tomkap** [comment]
After updating to 2.22 from 2.20 the rpki http server returns the following response (but at the moment the app works):
```
$ curl -6 http://rpki.example.com:8080/
curl: (52) Empty reply from server
$ curl -4 http://rpki.example.com:8080/
curl: (52) Empty reply from server
```

**Comment by omuravskiy** [comment]
Hi Thomas,

Could you paste here what's in the validator.log after it starts up?

**Comment by tomkap** [comment]
Ok, the app raised some exceptions about permission issues in subfolders. Fixed, with a simple "chown" and now everything works great. Sorry and thanks for your help.
