### ISSUE TITLE
Update rate

### ISSUE THREAD

**Issue by reuteran** [RIPE-NCC/rpki-validator#2]
Hey!

I've been wondering if there is a way to use custom update times for the trust anchors? 
I couldn't find anything in the conf file and I thought before digging through the source code I'd ask here first!

**Comment by omuravskiy** [comment]
There are now three configuration options available:

**validation.interval** defines a period between validation runs for a trust anchor.

**fetch.rddp.interval** and **fetch.rsync.interval** define a period of time within which already downloaded objects will not be updated from remote repositories, for RRDP and rsync repositories, accordingly.

I think this resolves the issue.
