### ISSUE TITLE
Warning at startup

### ISSUE THREAD

**Issue by bortzmeyer** [RIPE-NCC/rpki-validator#23]
```
rpki-validator.sh: line 64: ((: "9-internal" < 17 : syntax error: operand expected (error token is ""9-internal" < 17 ")
```

RPKI validator 2.23 

```
% java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)
```

**Comment by timbru** [comment]
Until now we have been quite restrictive in which java version is supported, as it says in the README.txt we have tested and support Oracle JDK 8. But it seems that the java version check in the start-up script  is somewhat naive about the expected format.

We are planning to do a lot of work on the validator starting mid May - immediately after the RIPE Meeting. We will investigate whether we can properly support other JDK versions. I do like the idea of supporting OpenJDK in particular, but can't promise anything yet. We can only 'officially' support it if we are confident that our code *and* the libraries we depend on are stable with those versions.
