### ISSUE TITLE
Absolute paths in HTML prevent validator webinterface to work behind ReverseProxy

### ISSUE THREAD

**Issue by sebastianw** [RIPE-NCC/rpki-validator#25]
I'm trying to put the validator behind an Apache webserver so that the website can be reached via SSL and on the standard port (443).

Apache Configuration looks like this:

```
ProxyPass        /rpki    http://localhost:8080/ nocanon
ProxyPassReverse /rpki    http://localhost:8080/
```
But then no assets can be loaded because they have hardcoded paths like this:
```html
        <link rel="stylesheet" href="/stylesheets/bootstrap/1.3.0/bootstrap.css" />
        <link rel="stylesheet" href="/stylesheets/application.css" />
        <script src="/javascript/datatables/1.8.2/jquery.js"></script>
```
It would be nice if the configuration would allow to configure a base-url value which I can set to the path I've set in the Proxy configuration.

**Comment by timbru** [comment]
Dear Sebastian,

I am sorry that I missed the notification for this issue.

Our main development effort now is on rpki-validator-3. We will have a basic release by the end of the year, with just an API and ROA csv/json output. We plan to work on a UI in January and February - we will take this on board as a requirement for that work: i.e. make it feasible set this up nicely using a proxy AND using a custom path.

I will close this issue for now hoping that a fix in validator-3 will be acceptable.
