### ISSUE TITLE
Things not quite right (2 TAs never update)

### ISSUE THREAD

**Issue by nzjc** [RIPE-NCC/rpki-validator#26]
I'm using:

`OS: RHEL 6.7`

```
Java:
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```
`rpki-validator-app-2.23`

When I log into the front end and click update all, all but 2 of the TAs work. 2 of them give me this:
`Object rsync://rpki.ripe.net/ta/ripe-ncc-ta.cer could not be retrieved. Returned code: 10, stderr: rsync: failed to connect to rpki.ripe.net: Connection refused (111) rsync error: error in socket IO (code 10) at clientserver.c(124) [receiver=3.0.6]`

I inititially had some firewall issues with rsync (none of the TAs worked) but that has been resolved (temporarily, by disabling iptables and firewalling where I understand  the workings a little better (back on the router used to control VM access)... So I don't *think* it's that. Why would it work for 8/10 TAs? 

Thanks

**Comment by omuravskiy** [comment]
Hi nzjc,

Since you are getting "Connection refused", my guess is it is because rpki.ripe.net has IPv6 address. Did you also disable ip6tables?

In case it still does not work, please test that you could either manually connect to the repository by issuing 

> rsync rsync://rpki.ripe.net/ta/ripe-ncc-ta.cer
(that should print 

> The RIPE NCC Certification Repository is subject to Terms and Conditions
> See http://www.ripe.net/lir-services/ncc/legal/certification/repository-tc
> 
> -rw-rw-r--         16,337 2017/05/09 15:50:59 ripe-ncc-ta.cer
),
or by connecting to rpki.ripe.net (both IPv4 and IPv6) port 873 with telnet, netcat, or something similar.

**Comment by nzjc** [comment]
Hi Oleg,

Yes I disabled ip6tables, iptables and shorewall (which invokes iptables).
```
[root@test-rpki james]# telnet rpki.ripe.net 873
Trying 2001:67c:2e8:22::c100:68a...
telnet: connect to address 2001:67c:2e8:22::c100:68a: Connection timed out
Trying 193.0.6.138...
telnet: connect to address 193.0.6.138: Connection timed out
```

My host is IPv6 enabled:
```
[root@test-rpki james]# telnet repository.lacnic.net 873
Trying 2001:13c7:7002:4128::144...
Connected to repository.lacnic.net.
Escape character is '^]'.
```

Thanks for the troubleshooting commands, I'll try and track down the problem and let you know.

**Comment by timbru** [comment]
Since we had no more news on this we assume this issue is closed. Please let us know if you still see problems.
