### ISSUE TITLE
Missing ARIN TAL

### ISSUE THREAD

**Issue by afenioux** [RIPE-NCC/rpki-validator#29]
The rpki-validator is shipped with some TAL but the ARIN is missing.
Would it be possible to include the ARIN TAL ?

If not possible, I think it would be worth mentioning it in the README or INSTALL file.

https://www.arin.net/resources/rpki/tal.html
https://www.arin.net/resources/rpki/arin-ripevalidator.tal

Thanks!

**Comment by timbru** [comment]
Hi,

Unfortunately we were expressly forbidden to include it, because ARIN wants users to download it from their site and thereby expressly accept their terms and conditions.

That said, I agree that we can and should include text on this in the README in an upcoming release.

Cheers
Tim
