### ISSUE TITLE
lib.OnlineNewVersionDetailFetcher fails - possibly due to IPv4-only socket calls

### ISSUE THREAD

**Issue by toreanderson** [RIPE-NCC/rpki-validator#3]
I get the following error logged to validator.log when running v2.17:

ERROR lib.OnlineNewVersionDetailFetcher: java.net.SocketException: Network is unreachable

I'm no Java expert, but the error message ("Network is unreachable") is in my experience indicative of IPv4-only socket calls, as this machine has no IPv4 addressing or connectivity. Had the external service been down, I would have expected "connection refused" or "connection timed out" or something similar. Also, standard tools gets the exact same error message, so I think the error message originates with the C library:

tore@rpki-validator:~$ ping 1.2.3.4
connect: Network is unreachable

Host environment:

tore@rpki-validator:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04 LTS
Release:    14.04
Codename:   trusty
OpenJDK 64-Bit Server VM (build 24.51-b03, mixed mode)
tore@rpki-validator:~$ uname -a
Linux rpki-validator.n.bitbit.net 3.13.0-30-generic #55-Ubuntu SMP Fri Jul 4 21:40:53 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
tore@rpki-validator:~$ java -version
java version "1.7.0_55"
OpenJDK Runtime Environment (IcedTea 2.4.7) (7u55-2.4.7-1ubuntu1)
OpenJDK 64-Bit Server VM (build 24.51-b03, mixed mode)

**Comment by timbru** [comment]
Hi Tore, unfortunately this got snowed under ages ago. My sincere apologies.

That being said our main development effort now is on rpki-validator-3. One of the goals there is to support Centos 7 RPMs, and possibly other popular distribution packages (contrib will be welcome!). Such that people can then add a repository, install the software and automatically keep it up to date and we don't need this custom 'update available checking' anymore.
