### ISSUE TITLE
Implementing RTR 1?

### ISSUE THREAD

**Issue by bortzmeyer** [RIPE-NCC/rpki-validator#30]
Now that RFC 8210 is published, are there plans to implement RTR version 1?

**Comment by timbru** [comment]
Hi Stephane, this is on our list for the rpki-validator-3 project that we are currently working on.

**Comment by bortzmeyer** [comment]
No need to close the ticket, tagging it as "working on it" or a similar label would have been more sensible.

**Comment by timbru** [comment]
I closed the ticket, because we are not fixing this on the 2.x release which is this project. We have an internal backlog for the 3.x release and will open a public github repository for it as soon as we have the first minimal working version available.
