### ISSUE TITLE
different release version on github/ripe website?

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [RIPE-NCC/rpki-validator#33]
https://lirportal.ripe.net/certification/content/static/validator/rpki-validator-app-2.24-dist.tar.gz  appears to be Java version and rpki-validator-2.24 release on github is docker version. I am not seeing docker mentioned in documentation/release notes.

Also download from https://lirportal.ripe.net/ in US is very slow over IPv4/IPv6

**Comment by timbru** [comment]
Hi,

The docker support was never 'official' so to say, but this is on our list to start supporting in our validator 3. See here: https://github.com/RIPE-NCC/rpki-validator-3

This project is currently still in pre-beta. We only have centos RPMs for now in repository that is about to get changed. But we're making good progress. We will also look into whether we can host the releases behind a CDN then.

I will keep this issue open and reply again when we have our first real beta versions available.

Kind regards,
Tim

**Comment by timbru** [comment]
We now have beta versions of the RPKI validator 3 available: RPM, docker and binary builds:
https://github.com/RIPE-NCC/rpki-validator-3/wiki/RIPE-NCC-RPKI-Validator-3-beta-tester-page

We expect to have our first production release within a couple of weeks.

Kind regards,

Tim
