### ISSUE TITLE
[ info ] rpki-validator is not running

### ISSUE THREAD

**Issue by minhdatvnpt** [RIPE-NCC/rpki-validator#39]
Hi everyone,
   I downloaded, un-tar and cd in the RPKI's root folder, then I implemented command to start and run RPKI Cache server:
[root@static rpki-validator-app-2.24]# ./rpki-validator.sh start
[ warn ] JAVA_HOME is not set, will try to find java on path.
[ info ] Starting rpki-validator...
[ info ] writing logs under log directory
[ info ] Web user interface is available on port 8080
[ info ] Routers can connect on port 8282
[ info ] Writing PID 12928 to validator.pid

[root@static rpki-validator-app-2.24]# ./rpki-validator.sh run
[ warn ] JAVA_HOME is not set, will try to find java on path.
[ info ] Starting rpki-validator...
[ info ] writing logs under log directory
[ info ] Web user interface is available on port 8080
[ info ] Routers can connect on port 8282

Then I checked status of RPKI, but it not worked:
[root@static rpki-validator-app-2.24]# ./rpki-validator.sh status
[ warn ] JAVA_HOME is not set, will try to find java on path.
[ info ] rpki-validator is not running
Why rpki-validator is not running? I missed some configuration or anything else? Please help me check?
- Information of my server:
   + Centos: 7
   + rsync:  version 3.1.2
   + rpki-validator-app-2.24
   + JAVA: openjdk version "1.8.0_181"
I'm sorry about my english :)

**Comment by lolepezy** [comment]
Hello, 
we believe this issue has been resolved with the 2.25 release.
