### ISSUE TITLE
Wrong protocol behavior

### ISSUE THREAD

**Issue by waehlisch** [RIPE-NCC/rpki-validator#6]
@job captured the following trace http://instituut.net/~job/rtrlib-over-ipv6.pcap, which shows (presumably) incorrect actions of the cache server.

(1) [Wrong Cache Reset] The Validator sends a Serial Notify with Serial Number=765 (packet no. 34). The client replies with a Serial Query including Serial Number=764. Then, the cache sends a Cache Reset, which indicates that they are out of sync.

Theoretically, the cache data can be changed between the Serial Notify and Serial Query. However, in this case, less than one second elapses between both messages. I suppose that the Validator expected a Serial Query including Serial Number=765. But this would not be correct according to RFC 6810 ("The Cache responds with all data records that have Serial Numbers greater than that in the router's query.") Can you verify?

(2) [Missing End of Data] After the Validator transmitted a bunch of prefixes - which have not been terminated with an End of Data PDU - the Validator initiates a Serial Notify (packet no. 319). Then a Cache Reset occurs, and the client receives again a bunch of prefixes and a Serial Notify (without End of Data PDU before). This repeats several times until the client terminates the whole RTR connection.

Before a Serial Notify follows prefix data (e.g., packet no. 319), I would expect an End of Data PDU.

RIPE Validator version 2.17.
RTR client is the RTRlib.

**Comment by waehlisch** [comment]
Hi Tim,

any news on fixing the issues? Actually, that the RIPE Validator doesn't support incremental updates gives us some headache. We started measurement of cache server consistency and this issue would bloat our log files ;). Furthermore, I know some AS operators that actually do RPKI filtering on their routers, and I suppose that this issue is not really appreciated by their routers ;).

Thanks
  matthias

cc @salsh

**Comment by timbru** [comment]
We plan to do a big re-implementation of the RPKI validator starting May this year.

Implementing full rpki-rtr-v2 compliance is part of that roadmap, but I cannot give an eta yet.

**Comment by waehlisch** [comment]
Got it. Then we have to wait.

**Comment by timbru** [comment]
Hi, I am closing this issue for this release for now. We plan to release an initial version of validator-3 before the end of the year. This version will come with an API and ROA json/CSV export only.

But we will work on full RPKI-RTR-v2 support, and an (optional) UI in Q1 2018.
