### ISSUE TITLE
RPM/Debian packages

### ISSUE THREAD

**Issue by dkowis** [RIPE-NCC/rpki-validator#8]
Came here from [the tweet](https://twitter.com/alexander_band/status/538304153853120512).
Making this so that I can document how the RPM/Deb's should look

For each project: 
- How do you want the installation to happen?
- Why is one project building a .tar.gz and the other building a .zip?
- The CLI builds a shaded jar, but the other uses a library directory, is this intentional?
- Do you want to put the shell scripts into `/usr/bin` so they show up as "real" binaries? (we'll need to change how it looks for `basedir`s)

For the validator-app
- There's a dist tarball that's created (although the root directory has zero permissions), do you want an extraction of that?
- What permissions do the directories within there need? (conf  data  lib log)
- Do you want a user for the thing, or install/run everything as nobody?
- Do you want an init script? (The shell script is almost an init script, but it needs some help)

No guarantees that I can do all this, but someone building the packages is going to need this info :)

**Comment by timbru** [comment]
We had no response for a while so we hope this addressed the issue. More importantly our main development effort is now on validator-3, and we want to make sure that packaging is done properly in that version.
